# Full configuration explanation in wiki
# Wiki: https://aglerr.gitbook.io/wiki/theonly-series/the-only-donations
####################################################################
# (options)
#   (useUUID) Should we use UUID when trying to get the player's head skin?
#             (Recommended set this to 'false' if you're on a cracked server)
options:
  useUUID: true

# Global discount setting (0 - 100).
# Example: If you set it to 40, all prices will be automatically discounted by 40%.
discount: 0

# Configuration Explanation
# (donationsMessage)
#   (messageWithAvatar)
#     (enabled) Should we use avatar images when donation is broadcasted?
#     (messages)
#       (header....footer) Messages that will appear when donation is being broadcasted
#   (messageWithoutAvatar)
#     (messages) Messages that will appear when donation is being broadcasted
#                 in condition if the (messageWithAvatar) is disabled.
#                 You can add as many lines as you want.
#
# Are you interested in using hex color? Check the wiki for example!
# Link: https://aglerr.gitbook.io/wiki/theonly-series/the-only-donations/plugins-files#example-usage

# You can make the donation goal always appear as a BossBar
bossbar:
  enabled: false # Enable this to use this feature
  # There are 3 Placeholder which is,
  # {current} is to show the current donation
  # {goal} is to show how much is the donation goal, you can see it at donationGoal:
  # {percentage} You can see what is the percentage at the Donation Goal
  title: "Current Donation Goal {current}/{goal}"
  color: "GREEN" # Color: BLUE, GREEN, PINK, PURPLE, RED, WHITE, YELLOW
  style: "SEGMENTED_10" # Segment: SOLID, SEGMENTED_6, SEGMENTED_10, SEGMENTED_12, SEGMENTED_20

discordWebhook:
  enabled: true
  url: "https://discord.com/api/webhooks/"
  embed:
    title: "New Donation! :tada:"
    description: "**{player}** baru saja berdonasi!"
    color: "#00d2ff"
    fields:
      - name: "Produk"
        value: "{product_displayname}"
        inline: true
      - name: "Harga"
        value: "Rp. {product_price}"
        inline: true
    thumbnail: "https://cdn.discordapp.com/attachments/1312840592178548876/1314314633707917312/seriagold.png?ex=6a17f0a3&is=6a169f23&hm=bb3631da0b3a3be40427a4eb62537b6cf9c077de6922d601dfa7a867fe6ae1f5&"

donationsMessage:
  messageWithAvatar:
    enabled: true
    messages:
      header: "&#00d2ff&m--------------------------------------------"
      line1: " &#00d2ff★ &#ffffff&l{player} &#aaaaaabaru saja berdonasi! &#00d2ff★"
      line2: ""
      line3: " &#00d2ff▪ &#ffffffProduk: &#00d2ff{product_displayname}"
      line4: " &#00d2ff▪ &#ffffffHarga: &#aaaaaaRp.{product_price}"
      line5: ""
      line6: " &#aaaaaaTerima kasih atas dukunganmu"
      line7: " &#aaaaaauntuk server Project Seria!"
      line8: " &#aaaaaa(( Kunjungi &#00d2ffstore.projectseria.com &#aaaaaa))"
      footer: "&#00d2ff&m--------------------------------------------"
  messageWithoutAvatar:
    messages:
      - "&#00d2ff&m--------------------------------------------"
      - " &#00d2ff★ &#ffffff&l{player} &#aaaaaabaru saja berdonasi! &#00d2ff★"
      - ""
      - " &#00d2ff▪ &#ffffffProduk: &#00d2ff{product_displayname}"
      - " &#00d2ff▪ &#ffffffHarga: &#aaaaaa{product_price}"
      - ""
      - " &#aaaaaa(( Kunjungi &#00d2ffstore.projectseria.com &#aaaaaa))"
      - "&#00d2ff&m--------------------------------------------"


# Configuration Explanation
# (events) List of events that will be played on donation perform
#   (effect) This event will give everyone a list of potions effects
#     (enabled) Should we enabled this event?
#     (effects) The list of potions effects that will be given to all players online
#               Format: POTION;AMPLIFIER;(DURATION (in seconds))
#               List of PotionEffectType https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html
#   (sound) The list of sounds that will be played upon donation
#           Format: SOUND_NAME;VOLUME;PITCH
#           List of Sounds: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
#   (titleBar) This event will send everyone a title bar message
#     (enabled) Should we enabled this event?
#     (title) The title of the title bar
#     (subTitle) The sub title of the title bar
#     (fadeIn) How long should the fade-in animation played? (in ticks - 20 ticks = 1 second)
#     (stay) How long should the title bar displayed? (in ticks - 20 ticks = 1 second)
#     (fadeOut) Howlong should the fade-out animation played? (in ticks - 20 ticks = 1 second)
#   (command) This event will executed a command from console
#     (enabled) Should we enabled this event?
#     (commands) A list of commands that will get executed
#                Available Placeholders:
#                - {player} - return the donor's name
events:
  effect:
    enabled: true
    effects:
      - "SPEED;3;30"
      - "JUMP;5;30"
      - "FAST_DIGGING;3;30"
      - "NIGHT_VISION;3;30"
  sounds:
    - "ENTITY_PLAYER_LEVELUP;1.0;1.0"
    - "BLOCK_LAVA_POP;1.0;1.0"
  titleBar:
    enabled: false
    title: "&#00d2ff&l{player} &#ffffffbaru saja berdonasi!"
    subTitle: "&#aaaaaaSemua pemain mendapatkan efek spesial!"
    fadeIn: 20
    stay: 60
    fadeOut: 20
  command:
    enabled: false
    commands:
      - "broadcast &aThanks {player} for the donation, everyone will receive a key!"
      - "crazycrates giveall virtual vote 5"

# Configuration Explanation
# (donationGoal)
#   (enabled) Should we enable donation goal module?
#   (donationGoal) How much is the donation goal?
#   (progressBar)
#     (barLength) How long is the progress bar?
#     (symbol) The symbol that will be used for the progress bar (Recommended: '|' or '█')
#     (completedColor) What is the completed color for the progress bar
#     (notCompletedColor) What is the un-completed color for the progress bar
#       Available Colors:
#       - AQUA
#       - BLACK
#       - BLUE
#       - DARK_AQUA
#       - DARK_BLUE
#       - DARK_GRAY
#       - DARK_GREEN
#       - DARK_PURPLE
#       - DARK_RED
#       - GOLD
#       - GRAY
#       - GREEN
#       - LIGHT_PURPLE
#       - RED
#       - WHITE
#       - YELLOW
donationGoal:
  enabled: false
  donationGoal: 500
  progressBar:
    barLength: 15
    symbol: '█'
    completedColor: GREEN
    notCompletedColor: RED
  commandsOnReach:
    - "broadcast &aWe have reached the donation goal!"

messages:
  noPermission: "&#ff5555Kamu tidak memiliki izin untuk melakukan ini!"
  reload: "&#55ff55Konfigurasi berhasil dimuat ulang!"
  invalidProduct: "&#ff5555Tidak ada produk dengan nama tersebut."
  performDonation: "&#55ff55Kamu telah mengirimkan donasi atas nama &#00d2ff{player}"
  reset: "&#55ff55Kamu telah mereset total donasi saat ini."
  help:
    - "&#00d2ff&lBantuan Donasi &#aaaaaa- Project Seria"
    - "&#00d2ff▪ /donations help &#aaaaaa- menampilkan pesan ini"
    - "&#00d2ff▪ /donations reload &#aaaaaa- memuat ulang konfigurasi"
    - "&#00d2ff▪ /donations reset &#aaaaaa- mereset donasi saat ini &#ff5555(EKSPERIMENTAL)"
    - "&#00d2ff▪ /donations send <player> <product> &#aaaaaa- menjalankan aksi donasi"
